### PR TITLE
code of conduct file added

### PR DESCRIPTION
**Pull request by pinak22dhir**
added code of conduct file 
issue number #4

### CODE REVIEW

**Comment by Sa2003hil** [comment]
@pinak22dhir It is good practice to include the issue number with which you have worked in the pull request.

**Comment by pinak22dhir** [comment]
@Sa2003hil resolved  issue number #4.

**Comment by Sa2003hil** [comment]
Thank you @pinak22dhir  , on submitting your very first pull request to the **Streamix IMDb** repository! 🥳

We will review this Pull Request and provide feedback as soon as possible!
We appreciate your patience and contribution, Keep up the great work! 😀
Don't forget to give a ⭐️to the repo ! ,for addition of hactoberfest label

**Comment by Sa2003hil** [comment]
👋 @pinak22dhir   We appreciate your patience and contribution !.
 Happy coding!. 😊

**Pull request merged**
