### PR TITLE
Feature/updated nav bar

### PR DESCRIPTION
**Pull request by Larkuo**
In this pull request I:
- Updated the navigation  bar with a search bar & sign-in button
Screenshot 2023-10-24 193249

- Added responsiveness & a sidebar to the navigation bar
Screenshot 2023-10-25 141402

Screenshot 2023-10-25 142009

Addresses Issue #1 

Edit: Screenshot of updated navigation bar & side bar below
image
image

### CODE REVIEW

**Comment by Sa2003hil** [comment]
👋 @Larkuo   **We appreciate your patience and contribution !.**
Don't forget to give a ⭐️ & Happy coding!. 😊

**Comment by Larkuo** [comment]
> 👋 @Larkuo   **We appreciate your patience and contribution !.**
> Don't forget to give a ⭐️ & Happy coding!. 😊

@Sa2003hil Thanks for the opportunity and your patience 🙏🏽😊

**Comment by Sa2003hil** [comment]
@Larkuo can you please create the pull request again ! somehow it is not showing in commits .. I think it's a glitch

**Comment by Larkuo** [comment]
@Sa2003hil Sure thing. I'll do that right away

**Comment by Sa2003hil** [comment]
image
this alert is comming !

**Comment by Larkuo** [comment]
I have just created a new [pr](https://github.com/Open-Source-Chandigarh/Streamix-IMDb/pull/23). Is that the one with the commit issue?

**Comment by Sa2003hil** [comment]
@Larkuo  now its working but there is some issue with width 
as you can see in the img signin button is not in correct positon
image

**Comment by Sa2003hil** [comment]
Now its working thanks for your contribution ! @Larkuo

**Comment by Larkuo** [comment]
Thank you for the opportunity! @Sa2003hil

**Comment by Sa2003hil** [comment]
@Larkuo acctualy there is some issue in your branch acctualy its merging for 10 mins only but after some time it is showing  an error if you can make changes directly in the main branch then it'll be merged ! Can you di it ?

**Comment by Larkuo** [comment]
@Sa2003hil Sure thing. I'll do that & update you shortly.

**Comment by Larkuo** [comment]
Hello @Sa2003hil I have created another pull request. Hopefully this one works

https://github.com/Open-Source-Chandigarh/Streamix-IMDb/pull/25

**Pull request merged**
