### PR TITLE
Added placeholder message

### PR DESCRIPTION
**Pull request by Pooja11kumari**
Added placeholder messages in contact us form of home page

### CODE REVIEW

**Comment by Sa2003hil** [comment]
@Pooja11kumari  Please add **issue number** with your pull request !

**Comment by Pooja11kumari** [comment]
Closes: #12

**Comment by Pooja11kumari** [comment]
@Sa2003hil Is it okay?

**Comment by Sa2003hil** [comment]
👋 @Pooja11kumari  Yes !  We appreciate your patience and contribution !.

Don't forget to give a ⭐️and Follow me **_@Sa2003hil_**  & Happy coding!. 😊

**Comment by Pooja11kumari** [comment]
@Sa2003hil Can you please add Hacktoberfest-accepted label to it.

**Comment by Sa2003hil** [comment]
@Pooja11kumari Sorry but ! its a very basic change ! you can choose another issue with **Hacktoberfest-accepted label**

**Comment by Pooja11kumari** [comment]
@Sa2003hil No iam asking you to add the label for this PR because i should submit the PR as a proof, and they are accepting only the PRs with Hacktoberfest-accepted labels.So if i start with a new PR,it will take 7 days to get verified .

**Comment by Sa2003hil** [comment]
@Pooja11kumari  Yes I know i've complete hacktoberfest ! but its a very basic change you have done that's why i did'nt add the label ... b/w I'll put a label on this as well.

**Comment by Pooja11kumari** [comment]
@Sa2003hil oh got it.But still Thanks a lot for adding.
Thank you

**Pull request merged**
