### PR TITLE
made changes in footer #9 issues fixed

### PR DESCRIPTION
**Pull request by BhukyaShivaNayak**
Hey added footer section . The footer section contains sign in button , other required links related to IMDb and I placed logo as per provided image sample . Used properties like flex and used font Awesome website for logos. The colors mostly used black,white and info .  which resolves issue( #9 )

### CODE REVIEW

**Comment by Sa2003hil** [comment]
@BhukyaShivaNayak Please add **proper description** of what you have done ans also add img !

**Comment by Sa2003hil** [comment]
@BhukyaShivaNayak Can you please add the image ! of what you have done

**Comment by BhukyaShivaNayak** [comment]
> Hey added footer section . The footer section contains sign in button , other required links related to IMDb and I placed logo as per provided image sample . Used properties like flex and used font Awesome website for logos. The colors mostly used black,white and info .

[https://app.gemoo.com/share/image-annotation/575478713976635392?codeId=M0GbXBQEwnkaY&origin=imageurlgenerator](url)

**Comment by BhukyaShivaNayak** [comment]
hey I don't Know how to add image .
let me try.
[image: Screenshot (161).png]

**Comment by Sa2003hil** [comment]
@BhukyaShivaNayak This img is not visible please take screenshot of your result img  then paste here !

**Comment by BhukyaShivaNayak** [comment]
I not getting how to share the image

**Comment by Sa2003hil** [comment]
@BhukyaShivaNayak  Ok let me explain firstly take screen shot **[win key + shift + s]** then select the portion then comeback here and paste it on this reply box !

**Comment by BhukyaShivaNayak** [comment]
this is ss

**Comment by Sa2003hil** [comment]
not visible ! you can check in preview section before commenting that is it visible or not then do the comment .

**Comment by BhukyaShivaNayak** [comment]
[Screenshot (161).pdf](https://github.com/Open-Source-Chandigarh/Streamix-IMDb/files/13123318/Screenshot.161.pdf)

**Comment by BhukyaShivaNayak** [comment]
[Screenshot (160).pdf](https://github.com/Open-Source-Chandigarh/Streamix-IMDb/files/13123768/Screenshot.160.pdf)

**Comment by Sa2003hil** [comment]
👋 @BhukyaShivaNayak   We appreciate your patience and contribution !.
Don't forget to give a ⭐️ & Happy coding!. 😊

**Comment by Sa2003hil** [comment]
@BhukyaShivaNayak Bro, I've merged it, but there are alignment issues. Please fix them. I've created a new issue.please make sure you first push the code then make changes.

**Comment by BhukyaShivaNayak** [comment]
Ok, I will check.

**Pull request merged**
