### PR TITLE
Underline Removed

### LINKED ISSUE #28: Remove Underline in the LOGO
**Describe the Issue**
Remove the Blue underline which is present in the NAV Logo.

**Screenshot**
Screenshot 2023-10-27 at 10 35 07 AM

### PR DESCRIPTION
**Pull request by Rakshithx7**
Underline which was present in logo is removed
CLOSES: #28

### CODE REVIEW

**Comment by Sa2003hil** [comment]
👋 @Rakshith-0-7   We appreciate your patience and contribution !.
Don't forget to give a ⭐️ & Happy coding!. 😊

**Comment by Rakshith-0-7** [comment]
Please add **"hacktoberfest-accepted"** Label.

**Comment by Rakshithx7** [comment]
@Sa2003hil Please add "hacktoberfest-accepted" Label

**Comment by Rakshith-0-7** [comment]
@Sa2003hil label of 'Hacktoberfest-accepted' has spelling mistake ,kindly correct it as soon as possible.('letter-k and captial H' is missing in label)

**Pull request merged**
