### PR TITLE
pr for issue#27

### PR DESCRIPTION
**Pull request by QuanHeMa**
hi！I have completed the task as required, I hope you can accept it, this is very important to me, thank you！solves issue #27

### CODE REVIEW

**Comment by Sa2003hil** [comment]
@QuanHeMa  please make sure that you add issue number in you pull request ! so that it is easy to find the issue detail

**Comment by QuanHeMa** [comment]
I have made the necessary modifications according to your requirements. If you have any questions, please feel free to contact me at any time

**Comment by Sa2003hil** [comment]
@QuanHeMa  please add screen shot of what you have done

**Comment by QuanHeMa** [comment]
line
I changed the structure and placed them in two rows

**Comment by Sa2003hil** [comment]
@QuanHeMa please add a proper gap between these two coloumns then again send me the screenshot

**Comment by QuanHeMa** [comment]
1MY74YCQ$9J}{GBE3FRTTKI
I have changed the font-size and gap

**Comment by QuanHeMa** [comment]
I'm a noob, so I'm not very skilled in operation, sorry.

**Comment by Sa2003hil** [comment]
image

some conflicts in your pr

**Comment by QuanHeMa** [comment]
S)DD5UE6Z5A2O_ ES`_WH70
I didn't change the code here, may I ask why it went wrong?

**Comment by Sa2003hil** [comment]
@QuanHeMa i think error is in your new branch please make changes direct to the main branch and make new PR

**Comment by Sa2003hil** [comment]
@QuanHeMa  again conflicts are there in your PR as i said earlier please delete you previous branch and make changes in the main branch than do a new PR

**Pull request closed without merging**
