### PR TITLE
Added Links to the Social Icons

### LINKED ISSUE #26: [BUG]Add links to the Logo's in Footer
**Describe the Issue**
1.Social logos in Footer are just Icons.Add Anchor tag to the logos with respective links.
2.Remove the Image in the footer “An AMAZON Company”

***Screenshot***
Screenshot 2023-10-27 at 10 06 38 AM

### PR DESCRIPTION
**Pull request by Pooja11kumari**
**Description**
Added Links to the Social Icons and also removed the "Amazon" logo bellow

Closes: #26

### CODE REVIEW

**Comment by Sa2003hil** [comment]
@Pooja11kumari Please add screen shot of what you have done !

**Comment by Pooja11kumari** [comment]
Social links:
Before:

https://github.com/Open-Source-Chandigarh/Streamix-IMDb/assets/143689177/80e01da4-5141-4d7c-a821-f4c073a48e8a

After:

https://github.com/Open-Source-Chandigarh/Streamix-IMDb/assets/143689177/2bc66fa5-fc6e-4b4f-8b0e-5c3beac9c85b


Amazon Logo:
before:
Screenshot 2023-10-30 at 12 32 06 PM

After:
Screenshot 2023-10-30 at 12 31 59 PM

**Comment by Pooja11kumari** [comment]
@Sa2003hil Please add Hacktoberfest-accepted Lable for the PR

**Comment by Sa2003hil** [comment]
👋 @Pooja11kumari   We appreciate your patience and contribution !.
Don't forget to give a ⭐️ & Happy coding!. 😊

**Pull request merged**
