### PR TITLE
added a footer section

### PR DESCRIPTION
**Pull request by BhukyaShivaNayak**
Hey hope you like it . I am happy to take feedback

### CODE REVIEW

**Comment by BhukyaShivaNayak** [comment]
Can please check it and give me a feedback .

**Comment by Sa2003hil** [comment]
Thank you @BhukyaShivaNayak  , on submitting your very first pull request to the **Streamix IMDb** repository! 🥳
Don't forget to give a ⭐️
We will review this Pull Request and provide feedback as soon as possible!
We appreciate your patience and contribution, Keep up the great work! 😀

**Comment by Sa2003hil** [comment]
Please take a refrence from this img 👍🏻 
image
and make changes according to this !

**Comment by Sa2003hil** [comment]
👋 @BhukyaShivaNayak   We appreciate your patience and contribution !.
**Don't forget to give a ⭐️** & Happy coding!. 😊

**Comment by BhukyaShivaNayak** [comment]
Does it count as hactoberfest contribution?

**Comment by Sa2003hil** [comment]
@BhukyaShivaNayak  Probably Yes ! you can check your hactoberfest profile ..

**Comment by BhukyaShivaNayak** [comment]
please add hactober label to it so i can make more changes to the footer
section

**Comment by Sa2003hil** [comment]
ok i'll create a new issue regarding this you can add assigning req there ! because this issue is closed now.

**Comment by BhukyaShivaNayak** [comment]
Okay

**Pull request merged**
